### ISSUE TITLE
Crash when opening file and changing size

### ISSUE THREAD

**Issue by lego290** [otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET#11]
Paint.net crashes when opening a svg file with a viewbox size of 272x78, and entering a width which results in a height equal to zero.

Currently i have to change one digit at a time, making sure the width value is never too small.

[pdncrash.1.log](https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/files/6101356/pdncrash.1.log)
[pdncrash.2.log](https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/files/6101357/pdncrash.2.log)
[pdncrash.3.log](https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/files/6101358/pdncrash.3.log)

**Comment by otuncelli** [comment]
Thanks. I'll look into this.

**Comment by Japollack** [comment]
I am having the same problem if changing the canvas height to 1080. It crashes as soon as I enter number 1.
It does not crash if I enter numbers like 2, 3, 4 or 5 etc.
The image I used locates here http://dicom.nema.org/medical/dicom/current/output/chtml/part03/figures/PS3.3_A.1-1.svg

**Comment by otuncelli** [comment]
Fixed in the latest release.
