### ISSUE TITLE
Incompatibility after switching Paint.Net to .net 5

### ISSUE THREAD

**Issue by iDolmatov** [otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET#13]
> C:\Program Files\paint.net\FileTypes\SvgFileType.dll, версии 1.0.0.0
> 
> Тип: System.Web.IHttpAsyncHandler
> System.TypeLoadException: Could not load type 'System.Web.IHttpAsyncHandler' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

More info: https://forums.getpaint.net/topic/117086-scalable-vector-graphics-filetype-alternative-plugin-svg-svgz/?do=findComment&comment=585068

**Comment by otuncelli** [comment]
Currently I'm working on this. I'll release a new .NET 5 compatible version in a day or two.

**Comment by otuncelli** [comment]
Should be fixed with the [latest release](https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/releases).

**Comment by iDolmatov** [comment]
Another error:
`C:\Program Files\paint.net\FileTypes\SvgFileType.dll, версии 1.0.3.0

System.IO.FileNotFoundException: Could not load file or assembly 'Svg, Version=3.2.0.0, Culture=neutral, PublicKeyToken=12a0bac221edeae2'. Не удается найти указанный файл.
File name: 'Svg, Version=3.2.0.0, Culture=neutral, PublicKeyToken=12a0bac221edeae2'
`

"Не удается найти указанный файл" = "File not found".

App version: 4.3 (α 4.300.7881.3082)
Runtime   .NET 5.0.8 x64

**Comment by iDolmatov** [comment]
For SVG project could only find old svg 0.5.2.0 library. With it, the program crashes when checking for plugin errors. You need to add the library to the archive.
Please use the folder in the archive so that the plugin and its additional library can be unpacked into their own folder and not depend on neighboring files.

Tried using svg.dll 3.2.3.36087 from JWL Helper. Then there is already a third party library error.
```
C:\Program Files\paint.net\FileTypes\SvgFileType\Svg.dll, версии 3.2.0.0

Тип: System.Web.IHttpAsyncHandler
System.TypeLoadException: Could not load type 'System.Web.IHttpAsyncHandler' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

I think that the plugin did not remove the library dependency check. Despite the presence of errors, the [test file](https://svgstudio.com/pages/free-sample) is loaded.
![image](https://user-images.githubusercontent.com/19782385/127763283-484e4aa5-c037-4412-ab0b-793e996bb091.png)

**Comment by otuncelli** [comment]
I see. I've used a new tool ([Costura.Fody](https://github.com/Fody/Costura)) to embed dependencies into the final binary. They should be dynamically loaded from resources and not the file system. You're right. Looks like it didn't remove the file system based dependency checking so it throws FileNotFoundException. I need to find a way to suppress this last error. Thanks for reporting. I'll prepare a hotfix in upcoming days.

Using [ILSpy](https://github.com/icsharpcode/ILSpy) tool:
Official Svg.dll has ASP.NET (System.Web namespace) dependency. Using this dll was causing the previous type loading error when using .NET 5 based Paint.net. It looks like Svg.dll from JWL Helper also has it.
![image](https://user-images.githubusercontent.com/5532796/127764159-29246bb8-6a13-425e-807a-83dd417c4708.png)

I've used customized Svg.dll.
![image](https://user-images.githubusercontent.com/5532796/127764412-ffccb6ed-4b0f-4434-8227-f542b1f8ad73.png)

You can download the ASP.NET dependency-free Svg.dll from here:
https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/tree/master/LibrariesWithoutASPNETDependency/net461

**Comment by iDolmatov** [comment]
The specified file excludes the error. As a workaround, you can add the file to downloads (Releases section).

**Comment by otuncelli** [comment]
Fixed with the latest release and it's still single dll file.

If possible, I'd rather prefer it to be a single dll to keep things nice and clean or my OCD throws an unhandled exception :smile:

**Comment by iDolmatov** [comment]
Solved. 
Thanks for the work you've done.
