### ISSUE TITLE
SVG is all black

### ISSUE THREAD

**Issue by the-r3dacted** [otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET#15]
Trying to open this SVG in paint.net doesn't work, no matter what option I pick, I only get a black square.

![Color](https://user-images.githubusercontent.com/77039240/172258129-89772ede-13ba-46a3-b6d0-8f3b87ed73dd.svg)

**Comment by 4n70w4** [comment]
Hi! The same issue!
paint net 4.3.12
plugin v1.05.1

**Comment by otuncelli** [comment]
Fixed in the latest release which uses a different rendering engine.

**Comment by the-r3dacted** [comment]
Plugin doesn't work at all anymore after updating
![ScreenShot_20230810234843](https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/assets/77039240/3ca00f91-ccbb-4712-9f7c-79f3fb21b9d1)

**Comment by otuncelli** [comment]
> Plugin doesn't work at all anymore after updating ![ScreenShot_20230810234843](https://user-images.githubusercontent.com/77039240/259919017-3ca00f91-ccbb-4712-9f7c-79f3fb21b9d1.png)

Only paint.net version 5.0.9 or later supported. You're on version 4.3.12.

**Comment by the-r3dacted** [comment]
Well my system can't run 5.x.

**Comment by the-r3dacted** [comment]
> > Plugin doesn't work at all anymore after updating ![ScreenShot_20230810234843](https://user-images.githubusercontent.com/77039240/259919017-3ca00f91-ccbb-4712-9f7c-79f3fb21b9d1.png)
> 
> Only paint.net version 5.0.9 or later supported. You're on version 4.3.12.

My computer can't run paint,net 5.x. I need a 4.3.12 compatible version please.

**Comment by otuncelli** [comment]
> > > Plugin doesn't work at all anymore after updating ![ScreenShot_20230810234843](https://user-images.githubusercontent.com/77039240/259919017-3ca00f91-ccbb-4712-9f7c-79f3fb21b9d1.png)
> > 
> > 
> > Only paint.net version 5.0.9 or later supported. You're on version 4.3.12.
> 
> My computer can't run paint,net 5.x. I need a 4.3.12 compatible version please.

Unfortunately I don't have a solution. I have neither the binaries nor Paint.net 4.3.12. You'll need to compile it yourself.
