### ISSUE TITLE
Unable to save as 'svg'; instead always saves as 'png'

### ISSUE THREAD

**Issue by afrowuk** [otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET#6]
- When you choose Save, it always saves as 'png' instead of 'svg' (despite having the correct file extension on the file name).
- When you choose Save As, it doesn't have the 'svg' file type in the file types drop down, and has 'png' selected. Again, the file name has the correct extension but the file type drop down overrides this.

This is with v0.3-alpha running on paint.net 4.2.8.

**Comment by otuncelli** [comment]
It's the normal behavior. Svg is a vector graphic format and Paint.NET can't be used to save this kind of formats. You have to use other programs (like Inkspace, CorelDRAW etc...) to edit or create svg files.
