### ISSUE TITLE
Default selection OK

### ISSUE THREAD

**Issue by Ecrfour** [otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET#8]
I suppose this isn't really an issue per-say, but when you click-and-drag SVG files into the program and open them, the thing selected by default is "cancel", making it much harder to spam enter to accept all of the settings. I would suggest changing this to have "OK" selected by default. Works great though, thanks for making this!

**Comment by otuncelli** [comment]
Yes, I see. I'll fix it. I'm glad you found this plugin useful. Thanks for reporting this.
